[project]
name = "chase-the-dot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "gymnasium>=1.3.0",
    "scipy>=1.15.0",
    "torch>=2.13.0",
    "torchvision>=0.28.0",
    "tqdm>=4.66.0",
    "pandas>=2.0.0",
    "matplotlib>=3.7.0",
    "notebook>=7.0.0",
    "seaborn>=0.13.2",
]

[project.scripts]
chase-the-dot = "chase_the_dot.run:main"
pid = "chase_the_dot.run:run_pid"
vpg = "chase_the_dot.run:run_vpg"
a2c = "chase_the_dot.run:run_a2c"
ddpg = "chase_the_dot.run:run_ddpg"
td3 = "chase_the_dot.run:run_td3"
sac = "chase_the_dot.run:run_sac"
ppo = "chase_the_dot.run:run_ppo"

[build-system]
requires = ["uv_build>=0.12.7,<0.13.0"]
build-backend = "uv_build"
